#!/bin/bash
# Evaluate helper script

echo "=================================="
echo "Missile PID Model Evaluation"
echo "=================================="
echo ""

# Model dosyasını bul
echo "1. Model dosyanızı bulun:"
echo "   Eğitim sırasında model şu klasörde kaydedilir:"
echo "   ./models/<experiment_name>/"
echo ""
echo "   İçinde şu dosyalar olabilir:"
echo "   - final_model.zip (eğitim sonunda)"
echo "   - best_model.zip (en iyi performans)"
echo "   - model_50000_steps.zip (checkpoint)"
echo ""

# Örnek komutlar
echo "2. Evaluation komutları:"
echo ""
echo "   # En basit kullanım:"
echo "   python evaluate.py --model_path ./models/EXPERIMENT_NAME/final_model.zip"
echo ""
echo "   # Daha fazla episode ile test:"
echo "   python evaluate.py \\"
echo "     --model_path ./models/EXPERIMENT_NAME/final_model.zip \\"
echo "     --n_episodes 20"
echo ""
echo "   # Farklı hedef tipi ile test:"
echo "   python evaluate.py \\"
echo "     --model_path ./models/EXPERIMENT_NAME/final_model.zip \\"
echo "     --n_episodes 10 \\"
echo "     --target_maneuver circular"
echo ""
echo "   # Tüm hedef tiplerini test et:"
echo "   for maneuver in straight circular zigzag evasive; do"
echo "     echo \"Testing \$maneuver...\""
echo "     python evaluate.py \\"
echo "       --model_path ./models/EXPERIMENT_NAME/final_model.zip \\"
echo "       --n_episodes 10 \\"
echo "       --target_maneuver \$maneuver \\"
echo "       --output_dir ./evaluation_results/\$maneuver"
echo "   done"
echo ""

echo "3. Model dosyanızı bulma:"
echo "   # Tüm model dosyalarını listele"
echo "   find ./models -name '*.zip' -type f"
echo ""
echo "   # En son kaydedilen modeli bul"
echo "   find ./models -name '*.zip' -type f -printf '%T@ %p\n' | sort -n | tail -1 | cut -d' ' -f2-"
echo ""

echo "=================================="
